name: Example Workflow

on: [push]

env:
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Build the app
      run: npm run build

    - name: Test the app
      run: npm test

    - name: Deploy the app
      env:
        API_KEY: ${{ env.API_KEY }}
      run: |
        echo "Deploying the app using API Key: $API_KEY"
        # your deployment commands go here

