name: Deploy Website

on:
  push:
    branches:
      - main

env:
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 12

    - name: Build and Deploy
      run: |
        echo "API_KEY=${{ env.API_KEY }}" >> .env
        npm run deploy
